assert_input_phenomena(5):-
    assert(event_instant(drop(bob,coin),1)),
    assert(event_instant(hunger(bob),1)),
    assert(event_instant(hunger(alice),1)),
    assert(event_instant(pickup(bob,coin),3)),
    assert(event_instant(drop(bob,wallet),3)),
    assert(event_instant(pickup(alice,wallet),4)),
    assert(event_instant(drop(bob,torch),5)).
assert_input_phenomena(10):-
    assert(event_instant(pickup(alice,flower),6)),
    assert(event_instant(pickup(bob,wallet),6)),
    assert(event_instant(drop(bob,coin),8)),
    assert(event_instant(ate(bob,food),8)),
    assert(event_instant(drop(alice,wallet),9)),
    assert(event_instant(pickup(alice,coin),9)),
    assert(event_instant(pickup(bob,tobacco),10)).
assert_input_phenomena(15):-
    assert(event_instant(hunger(bob),13)),
    assert(event_instant(ate(alice,food),14)),
    assert(event_instant(drop(bob,pen),15)).

